### ISSUE TITLE
*[data-tutorial] selektor

### ISSUE THREAD

**Issue by tenhobi** [Jahoda/tutorial#1]
V čem je využití selektoru `*[data-tutorial]` lepší oproti `[data-tutorial]`? Prohlížeči to zbytečně přidá kroky navíc, ne? Tedy pokud si to nějak dodatečně neoptimalizuje. :smirk_cat:

**Comment by Jahoda** [comment]
Hm, tipoval bych, že je to úplně jedno. Ale nějaký výzkum jsem kolem toho neprováděl.

**Comment by tenhobi** [comment]
Prohlížeč selektory zpracovává zprava doleva, důvody viz http://stackoverflow.com/a/5813672/3281252. U každého elementu se tedy zeptá: "Obsahuje daný element [data-tutorial]?" a pokud ano, jede dál a ptá se: "Je tento element jakýkoli?", což by teoreticky mohlo o pár malinkatičkých jednotek času zpomalit celý proces stylování. Tedy za předpokladu, že si prohlížeč selektory nejdříve neoptimalizuje, z toho by tu \* nejspíše odstranil, protože to je zbytečné pravidlo. :smirk_cat:

**Comment by Jahoda** [comment]
> Tedy za předpokladu, že si prohlížeč selektory nejdříve neoptimalizuje, z toho by tu \* nejspíše odstranil, protože to je zbytečné pravidlo. 

Tak nějak jsem to myslel. Přijde mi, že není důvod mezi těmi selektory rozlišovat.
